# Generated by Django 3.1.4 on 2021-01-01 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0002_auto_20210101_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vinculo',
            name='nome',
            field=models.CharField(max_length=100),
        ),
    ]
